name: Build on push or pull request

on: [ push, pull_request ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: build --scan --stacktrace --warning-mode all
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package-${{ matrix.os }}
          path: |
            JarTighten/build/libs
            JarTighten-lib/build/libs
            JarTighten-plugin/build/libs
